backend="glx";
vsync=true;
dithered-present=true;
use-damage=false;
xrender-sync-fence=true;
corner-radius=8;

shadow=true;
shadow-radius=12;
shadow-opacity=0.35;

fading=true;
fade-in-step=0.1;
fade-out-step=0.1;
